### ISSUE TITLE
Introduce Custom Interceptors

### ISSUE THREAD

**Issue by gldiazcardenas** [taboola/api-java-client-core#6]
It would be great to have the possibility to add custom interceptors defined by the client to add some extra steps in the requests processing flow.

Possible use cases:
- Limit the amount of API calls made in a central/clean manner.
- Log api calls to a database.
- Add custom headers to the request.

**Comment by vladimanaev** [comment]
Hi @gldiazcardenas ,

Bullet one and two gonna be covered in #9 
Bullet three already supported by "setHeaders" on client builder
